/********************************************************************
* utils/Analysis_dict_utils.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error utils/Analysis_dict_utils.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAnalysis_dict_utils();
extern void G__cpp_setup_inheritanceAnalysis_dict_utils();
extern void G__cpp_setup_typetableAnalysis_dict_utils();
extern void G__cpp_setup_memvarAnalysis_dict_utils();
extern void G__cpp_setup_globalAnalysis_dict_utils();
extern void G__cpp_setup_memfuncAnalysis_dict_utils();
extern void G__cpp_setup_funcAnalysis_dict_utils();
extern void G__set_cpp_environmentAnalysis_dict_utils();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "utils/ParticleData.hh"
#include "utils/Config.hh"
#include "utils/Constants.hh"
#include "utils/RooUtils.hh"
#include "utils/RooFitUtils.hh"
#include "utils/ObjectStore.hh"
#include "utils/KineUtils.hh"
#include "utils/StatUtils.hh"
#include "utils/CfgParser.hh"
#include "utils/FileUtils.hh"
#include "utils/StringUtils.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Analysis_dict_utilsLN_TClass;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TBuffer;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMemberInspector;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TObject;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TNamed;
extern G__linked_taginfo G__Analysis_dict_utilsLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__Analysis_dict_utilsLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_string;
extern G__linked_taginfo G__Analysis_dict_utilsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TParticlePDG;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TDatabasePDG;
extern G__linked_taginfo G__Analysis_dict_utilsLN_ParticleData;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TStyle;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TH1;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooUtils;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TCanvas;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooPlot;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooAbsReal;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooRealVar;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooDataSet;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooAddPdf;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooAbsPdf;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooArgList;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooFitResult;
extern G__linked_taginfo G__Analysis_dict_utilsLN_RooFitUtils;
extern G__linked_taginfo G__Analysis_dict_utilsLN_maplETObjectmUcOTObjectmUcOlesslETObjectmUgRcOallocatorlEpairlETObjectmUsPconstcOTObjectmUgRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_TVector3;
extern G__linked_taginfo G__Analysis_dict_utilsLN_KineUtils;
extern G__linked_taginfo G__Analysis_dict_utilsLN_StatUtils;
extern G__linked_taginfo G__Analysis_dict_utilsLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_listlEEventHeadercOallocatorlEEventHeadergRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__Analysis_dict_utilsLN_FileUtils;
extern G__linked_taginfo G__Analysis_dict_utilsLN_StringUtils;

/* STUB derived class for protected member access */
typedef vector<float,allocator<float> > G__vectorlEfloatcOallocatorlEfloatgRsPgR;
